### ISSUE TITLE
USER STORY: Set up REACT Front End GitHub Repository

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#10]
As a developer, I need to set up a separate repository to create the front end user interface using the REACT library and react bootstrap styling.

**Acceptance Criteria:**

     1. New GitHub repository with appropriate name for PP5 REACT Front End
     2. Able to use repository to create workspace in GitPod
     3. Working Add, Commit and Push functionality

**Tasks:**

- [x] Using CI Template, create new repository
- [x] Log into GitPod and create new Workspace for the new Repository
- [x] Use git add, commit and push for initial commit.
