### ISSUE TITLE
USER STORY: Set up Project Kanban Board with labels and milestones

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#11]
As a developer, I need to create a KanBan Board with defined user stories, epics, MoSCoW prioritisation and sprints to enable me to use AGILE working methodologies and keep on top of my project. 

**Acceptance Criteria:**

      1. The project Kanban Board contains Epics broken down into User Stories for each step of the development process 
      2. Each User Story has been assigned a MoSCoW label and attached to a proposed milestone Sprint for completion 
      3. The User Stories are organised in the expected order of progress 

**Tasks:**

- [x] Create Board and Issue Templates 
- [x] Update labels and milestones
- [x] Add Epics for key development stages
- [x] Add User Stores
- [x] Assign appropriate User Stories to a particular Epic
- [x] Add Acceptance Criteria and Tasks to each user story
- [x] Add MoSCoW labels, Story Points and assign to sprints
