### ISSUE TITLE
USER STORY: Deploy DRF API to Heroku

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#13]
As a developer, I need to deploy my api back end project to Heroku so that there is a cloud-based version of my project for testing and assessment

**Acceptance Criteria:**

      1. Working deployed application hosted in Heroku
      2. DEBUG setting is set to False
      3. All sensitive data is included in env.py file to keep it secure

**Tasks:**

- [x] Create Heroku App
- [x] Link Heroku app to GitHub Repo
- [x] Update code ready for deployment (e.g. requirements.txt)
- [x] Ensure you have a Procfile
- [x] Ensure the database url is included in the env.py
- [x] Add, Commit and Push to GitHub
- [x] Update Config Vars in Heroku
- [x] Deploy branch manually in Heroku and open to check it works
