### ISSUE TITLE
USER STORY: Deploy REACT Front End to Heroku

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#14]
As a developer, I need to deploy my REACT front end project to Heroku so that there is a cloud-based version of my project for testing and assessment

**Acceptance Criteria:**

      1. Working deployed REACT application hosted in Heroku
      2. Displays expected UI Components and Placeholder Text
      3. 

**Tasks:**

- [x] Add placeholder text to App.js to display in REACT preview
- [x] Ensure all required document files are installed following CI walkthrough setup guidance.
- [x] Log in and create new app in Heroku
- [x] Connect GitHub repository in Deploy tab and click on Deploy Branch
- [x] Once built, open app and check that placeholder text displaying as expected.
