### ISSUE TITLE
USER STORY: Define Database Models & Create ERDs

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#16]
As a developer, I can create an ERD for each database model so that I have a blueprint to use when creating the model

**Acceptance Criteria:**

      1. Complete ERD available for each data model
      2. Each ERD includes all fields, field types, authentication and key info

**Tasks:**

- [x] List all required data models (relating to each page of the site)
- [x] Create an ERD for each model
- [x] Add ERDs to README files
