### ISSUE TITLE
USER STORY: Map out Model Schema

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#17]
As a developer, I can create a model schema so that I have a blueprint for a database that defines how data is organised and connected

**Acceptance Criteria:**

     1. A schema diagram containing an ERD for each model
     2. Relationships between primary and foreign keys are shown
     3. 

**Tasks:**

- [x] Identify how each Django view will request data from each model to display in a Rest resource
- [x] Identify any Primary / Foreign Keys and dependencies
- [x] Add ERD for each model and to schema diagram
- [x] Add visual representation of relationships between models
- [x] Add schema diagram to README files
