### ISSUE TITLE
USER STORY: Tailored Navigation

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#19]
As a casual user, I want to see only the navigation items that I can access such as Sign In and Sign Up so that I am not clicking on links that I am not authrorised to access.
As an authenticated user, I want to see only the navigation items that I need such as Sign Out, Nominate a Business, and Profile.

**Acceptance Criteria:**

      1. When not logged in, user sees only Home, Sign In and Sign Up links in the NavBar
      2. When logged in, the Sign In and Sign Up links are not visible and Sign Out and Add a Business are displayed
      3. When logged in, the user sees their own name and profile avatar in the top right corner of the page

**Tasks:**

- [x] Define required links for logged in / logged out users
- [x] Create const loggedInIcons and const loggedOutIcons to select links to show when user logged in.
- [x] Set if / else statement in NavBar.js after Browse link (shows whether logged in or not) to toggle between loggedInIcons or loggedOutIcons content (navlinks)
- [x] Reload dev project and check if only Browse and 'loggedOutIcons' displaying
- [x] Once logged in, check only 'loggedInIcons displaying.
