### ISSUE TITLE
USER STORY: Submit My Business

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#2]
As a business owner, I want to fill in a form to submit my business to the directory so that it can be listed and gain more visibility.

**Acceptance Criteria:**

      1. A company owner can click on an Add My Company link to enter their company details in a form.
      2. When the form is submitted, the company is added to the api and is listed when you add /companies to the deployed api url.
      3. Upon submission, the user is redirected to the company details page for the company just submitted.

**Tasks:**

- [x] Link the form to a new route in App.js
- [x] Create a CompanyCreateForm and include all of the fields in the Company model of the api.
- [x] Define the companyData and include all model fields and the data type for processing.
- [x] Create handlers for changing the content of a field, the logo image and submitting the data to the api. 
- [x] Ensure errors are in place for each field.
- [x] Complete the form including all required details and submit
- [x] Ensure that you are redirected to a url for /companies/1 with the company id included at the end of the url
- [x] Open the deployed Heroku api and add /companies to the end of the url to check if the new company is listed.
