### ISSUE TITLE
USER STORY: Log In

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#20]
As an authenticated user, I can sign in to the application so that I can see my profile / business listing, endorse businesses and leave comments

**Acceptance Criteria:**

     1. Registered User and Administrator can complete a Sign in form and Sign in via a link in the navigation bar
     2. User is shown appropriate content for their access rights
     3. If not registered user or admin, user is given error message and redirected to registration page.

**Tasks:**

- [x] Create a Sign In Form similar to the Sign Up Form
- [x] Add methods to get user data from the API and handle changing and submitting this data in the form
- [x] Import SignInUpForm styling for consistent look and feel
- [x] Set up redirection to registration / sign up page if sign in error
- [x] Test that the username displays in the navbar when logged in
