### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#21]
As an authenticated user, I can log out of the site so that if my device is left unattended others cannot access areas that are not meant for them

**Acceptance Criteria:**

      1. When logged in, Registered Users and Staff Administrators can log out by clicking on a 'Log Out' button
      2. Once logged out user only sees appropriate navigation links in NavBar such as Home, Sign Up and Sign In

**Tasks:**

- [x] Create async handleSignOut method to use Try and Catch statement posting to dj-rest-auth/logout/
- [x] Call handleSignOut method using onClick in the attributes for the Sign Out NavLink
- [x] When logged in, check that Sign Out icon and link display in navigation bar
- [x] Check that user is logged out when Sign Out link clicked and logged out icons display once again
- [x] Redirect users to Browse (home) page
