### ISSUE TITLE
USER STORY: Implement User Registration

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#22]
As a user, I can register on the site so that I can add my own business listing, endorse companies and leave comments

**Acceptance Criteria:**

      1. Unregistered users can submit a registration form to register on the site
      2. Appropriate fields are included in the form component so that  
      3. Once registered the user can log in immediately

**Tasks:**

- [x] Set up permissions.py and serializers.py in REST api
- [x] Install allauth 0.54.0 and dj-rest-auth 2.1.9 in REST api to manage user registration
- [x] Check using Django version 4.2 to ensure compatibility and remove 'allauth.account.middleware.AccountMiddleware', if present in settings.py middleware.
- [x] Create a superuser and log in to test that you can see admin page for REST-api
- [x] Create pages/auth folder in REACT Front End project
- [x] Create SignUpForm.js
- [x] Install axios and set up src/api/axiosDefaults.js in REACT Front End
- [x] Add SignInUpForm.module.css with react-bootstrap styling to render Sign Up form as preferred
- [x] Add SignUpForm route to App.js
