### ISSUE TITLE
USER STORY: Set Up CSRF Tokens and Cookies

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#23]
As a developer, I need to connect my back end API with my front end UI so that requests and responses are authorized and data can be passed and manipulated between the two

**Acceptance Criteria:**

      1. The CSRF tokens and JWT cookies set up in the REST api settings.py allow the user to log in via the SignInForm.js page in REACT dev UI
      2. Heroku Config Vars are correctly set up to enable the REACT Front End to talk to the Back End REST api
      3. When logged in, the authenticated user's name is shown in the NavBar.

**Tasks:**

- [x] Add corseheaders.middleware.CorsMiddleware is added to the top of MIDDLEWARE in settings.py
- [x] Add corsheaders to INSTALLED_APPS
- [x] Check JWT cookie configurations correct in settings.py
- [x] Check CLIENT-ORIGIN and CLIENT_ORIGIN_DEV settings are correct and CORS_ALLOW_CREDENTIALS = True
- [x] Add DATABASE_URL to env.py for PostgreSQL database URL.
- [x] Create Sign Up and Sign In forms in front end REACT UI and register a new user
- [x] Check registration successful by add /profiles/ to end of deployed api url to see if new user listed.
