### ISSUE TITLE
USER STORY: Moderate Submissions

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#25]
As an admin, I want to review new business submissions to ensure they meet the eco-positive criteria before listing them.

**Acceptance Criteria:**

      1. An authenticated admin (superuser) can access all submitted company profiles and can 'approve' new business profiles so that they are listed in the directory.
      2. When submitting a new business, the business owner is requested to submit a professional / company email address that will be contacted to verify that it is an authentic business and confirm that they are authorised to add the business to the directory.
      3. An admin page displays all new companies that have not yet been approved so that the admin can view the company and update the approved status to true.

**Tasks:**

- [x] Create an AdminPage parent component and a NewCompany.js file for the component to be included in the list
- [x] Use a fetchData method to retrieve the companies data and profile data
- [x] Check that the current user has 'admin_access' : true and add conditional rendering to render content only if admin.
- [x] Add the route for the AdminPage to App.js and include a link in the navbar with conditional rendering so only visible to admins.
- [x] Add an 'Approve' button the NewCompany component with a handleApprove method to update the approved field in the Company model.
- [x] Add styling to ensure list of new companies to approve displays well and is responsive.
- [x] Check that the approved field is updated correctly when the Approve button is clicked.
- [x] Check that the approved company is removed from the list of newCompanies to approve and is no longer rendered to the AdminPage.
