### ISSUE TITLE
USER STORY: Moderate Comments

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#26]
As an admin, I want to moderate user comments to prevent spam or inappropriate content.

**Acceptance Criteria:**

      1. When logged in as an admin, all reported comments can be accessed via the admin page.
      2. The admin can review a comment and decide if it should be changed back to 'approved' or if it should be deleted.
      3. The admin clicks a button to approve or delete the comment and it is removed from the admin page.

**Tasks:**

- [x] Use fetchData method in AdminPage to retrieve and filter a list of comments with 'reported === true.
- [x] Map through reportedComments and assign each comment to a 'ReportedComment' component.
- [x] Create 'ReportedComment' component with handleApprove and handleDelete functionality for buttons
- [x] Add styling to display on the Admin Page consistently with rest of site and New Companies list
- [x] Check that when approved, comment is displayed as usual on CompanyPage.
- [x] Check that when deleted, comment is no longer displayed on CompanyPage and comment_count reduces by 1.
