### ISSUE TITLE
USER STORY: Explore Businesses

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#29]
As a user, I want to browse a list of eco-friendly and socially conscious businesses in Bristol so that I can discover new places to support.

**Acceptance Criteria:**

      1. Whether logged in or not, a list of all businesses is displayed on the 'home' page Directory component featuring the company name, logo, a brief excerpt describing the company and a list of their eco-credentials for quick reference.
      2. The Directory has bottomless scrolling functionality so that users can continue browsing all businesses without clicking on any navigation buttons.
      3. Clicking on the logo or name of a company takes the user to that company's details page.

**Tasks:**

- [x] Add CompanyListPage to UI adapated from Moments walkthrough
- [x] Add CompanyList component to display briefe overview of company details
- [x] Create methods in CompanyList to retrieve company credentials
- [x] Filter credentials by group and add jsx to render groups if any credentials present in that group list
- [x] Add styling to ensure responsiveness
- [x] Add links on logo and company name to take user to CompanyPage
- [x] Add CompanyList component to CompanyListPage and check it renders as expected.
- [x] Check that links take the user to the correct CompanyPage.
