### ISSUE TITLE
USER STORY: Update My Business Listing (CRUD)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#3]
As a business owner, I want to update my listing description and other details so that potential customers have accurate information.

**Acceptance Criteria:**

      1. When logged in, an authenticated business owner can click an edit icon on a drop down menu in the company details page to view the EditBusinessForm which is the same as the AddBusinessForm but with pre-populated information to be updated.
      2. Once edited, clicking on 'Submit Changes' shows the business owner the newly updated details page.  
      3. Clicking on 'Cancel' takes the user back to the original business details page.

**Tasks:**

- [x] Create a CompanyEditForm using the same format as the CompanyCreateForm.
- [x] Set the company id using useParams()
- [x] Create useEffect function with handleMount to retrieve company data and enable owner to update data items. 
- [x] Amend handleSubmit to use axiosReq.put () instead of post to indicate an update.
- [x] Manage logo image separately to check if already an existing file attached and to use current file.
- [x] Manage credentials separately by retrieving from company data first, then use same axios.patch() to save credentials array to credentials field in Company model within the handleSubmit method.
- [x] Try editing company content to check it updates as expected.
- [x] Try changing the logo to check that is updated as expected.
- [x] Check that all the same credentials attached to a company before editing are still attached once edits are submitted.
