### ISSUE TITLE
USER STORY: Filter My Endorsements in a profile page

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#31]
As a user, I want to filter businesses that I have endorsed so that I can identify additional companies I would like to endorse.

**Acceptance Criteria:**

      1. When logged in an authenticated user can click on a 'My Endorsed Only' button to filter the Directory list so that it shows only businesses that they have previously endorsed and the button text changes to 'List All'.
      2. When the user clicks on the same 'List All' toggle button, the full Directory is once again displayed.
      3. When clicked, the button changes colour and the text is updated to display to the user which filter setting they are viewing.

**Tasks:**

- [x] Create a profile page container for 'My Endorsed Companies'
- [x] Filter all companies data by mapping 'endorsed_users' against the currentUser and return any matches to the endorsedCompanies list 
- [x] Import the CompanyList component to the profile page and render each endorsed company into a CompanyList component
- [x] Include a tally at the top of the page to highlight the number of endorsed companies and appropriate messaging if none available
- [x] Use conditional rendering to remove the My Companies section if the user has not submitted any companies of their own.
