### ISSUE TITLE
USER STORY: View Top Businesses

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#32]
As a user, I want to see the top businesses with the most endorsements on the homepage so I can quickly find the most popular companies.

**Acceptance Criteria:**

      1. When browsing the Directory in the CompanyListPage component, users are shown a TopCompanies component featuring the 5 companies with the most endorsements on desktop and the 3 companies with the most endorsements on mobile devices.
      2. The top companies list includes the company name, logo and a link to their company details page.
      3.

**Tasks:**

- [x] Add a TopCompanies component to files
- [x] Add a TopCompany component to set the rendering layout and style for each top company
- [x] Add a handleMount method to filter all companies with one or more endorsements
- [x] Sort the endorsed companies array in descending order and slice the top three results to create the topCompanies list to display.
- [x] Import the TopCompany component to TopCompanies and map the topCompanies list to display the TopCompany component for each of the top companies.
- [x] Check responsiveness works on smaller and bigger devices as expected.
