### ISSUE TITLE
USER STORY: Search by Key Word

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#33]
As a user, I want to search for particular kinds of business so that I can see which ones can offer what I need and have good eco-credentials.
**Acceptance Criteria:**

      1. A user who is looking for a particular kind of company can search a set of key words provided by the business owner that are associated with their company. 
      2. Users can enter the key word into a search bar at the top of the page and any companies that match the search word are listed.
      3. If there are no companies listed for that word, the user sees a message and an image stating that there don't appear to be any companies listed matching your search. Try searching for something else. 

**Tasks:**

- [x] Add a Key Words field to the Company model
- [x] Include the Key Words field in the search fields within the companies Views.py
- [x] When rendered in the REACT UI, use the search bar to check for a word that you know is included in the key words to check that the expected company displays
- [x] When rendered in the REACT UI, use the search bar to check for a word that you know is NOT included in the key words to check that companies do not display if they do not have this word in their searchable fields.
