### ISSUE TITLE
USER STORY: Search by Business / Organisation Name 

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#34]
As a user, I want to search for particular business by name so that I can check their eco-credentials and endorsements.

**Acceptance Criteria:**

      1. Any user can enter the name or part name of a company in a search bar at the top of the Directory page to see if that company is listed and what their credentials are.
      2. If a company does not exist or cannot be found, the user sees a message and an image to state that there doesn't appear to be a company listed with that name.
      3.

**Tasks:**

- [x] Add a search bar to the CompanyListPage adapted from Moments walkthrough
- [x] Update placeholder text
- [x] Ensure No Results image uploaded to assets
- [x] Check that REST api has all relevant search fields included in companies.views.py
- [x] When several companies have been added, search by selection of words to ensure list filters working correctly.
