### ISSUE TITLE
USER STORY: Endorse Businesses

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#35]
As a user, I want to endorse businesses I trust so that others can see which ones have strong community support.

**Acceptance Criteria:**

      1. When viewing the Company Details page an authenticated user can click on an 'Endorse this Company' toggle button to add their own endorsement to the company listing. 
      2. When the 'endorse' button is clicked, the endorsement count increases by 1
      3. If the logged in user is the company owner they are not able to endorse their own company.

**Tasks:**

- [x] Add Endorsement model to DRF API and test
- [x] Add validation to views to raise a validation error if the current logged in user is the owner of the company being endorsed
- [x] Add buttons and conditional rendering to UI Company component for adding an endorsement.
- [x] Adapting approach used for likes in Moments walkthrough, create handlers to handleEndorse for a company.
- [x] Check that all fields in api serializers match fields in UI to be updated when endorsement created
- [x] Use log errors to console to resolve any issues.
- [x] Check that conditional rendering displaying correct content and styling and endorsements_count increases when endorsements are added.
- [x] Check that different users (company owners / previous endorsers / casual users) are shown the correct content.
