### ISSUE TITLE
USER STORY: Remove Business Endorsement

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#36]
As a user, I want to be able to remove my endorsement of a business if I change my mind.

**Acceptance Criteria:**

      1. When viewing the company details page for a company that an authenticated user has previously endorsed, the user can click on the same button to remove their endorsement of that business.
      2. When removed, the user sees a confirmation message to confirm that they no longer endorse this company.
      3. When the 'remove endorsement' button is clicked, the endorsement count decreases by 1

**Tasks:**

- [x] Add buttons and conditional rendering to UI Company component for removing an endorsement.
- [x] Adapting approach used for likes in Moments walkthrough, create handlers to handleUnendorse for a company.
- [x] Use log errors to console to resolve any issues.
- [x] Check that conditional rendering displaying correct content and styling and endorsements_count decreases when endorsements are removed.
- [x] Check that different users (company owners / previous endorsers / casual users) are shown the correct content.
