### ISSUE TITLE
USER STORY: Edit a Comment (CRUD)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#39]
As a user, I want to edit my own comments on a business’s profile so I correct any mistakes or want to expand / change my comment at a later time.

**Acceptance Criteria:**

      1. When logged in, an authenticated user can view the comments that they have submitted and click on an edit icon to update the comment.
      2. The user is shown the EditCommentForm which is the same as the CommentForm but with pre-populated content to be updated.
      3. When updated, the new comment is displayed in the Comments component with 'Edited x days ago' to show the time elapsed since it was updated.

**Tasks:**

- [x] Import Dots dropdown menu to comment component
- [x] Add validation to check if the current user is the comment owner then display dropdown
- [x] Add CommentEdit form using CommentCreate form as template
- [x] Create handleEdit method to display the CommentEdit form within the CompanyPage when edit option selected in dropdown
- [x] Select a comment to edit and check that CommentEdit form displays when icon clicked
- [x] Update the content and check that updated content rendered as expected.
