### ISSUE TITLE
USER STORY: Add Eco-Credentials to My Business

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#4]
As a business owner, I want to add the eco credentials that relate to my company to highlight our environmental and social awareness

**Acceptance Criteria:**

      1. When logged in and authenticated, a business owner can select from a range of 'eco-credentials' by clicking on each one that applies to their company.
      2. Credentials are listed under group headings to help the Business Owner easily find the ones that best fit
      3. Owners can also remove a selected credential if they wish.

**Tasks:**

- [x] Add credentials to the api as admin SuperUser
- [x] Create a CredentialSelectForm.js file in REACT
- [x] Use fetch to retrieve all credentials data from api.
- [x] Create a drop down menu for all credentials
- [x] Use handler methods to manage the addition of new credentials to existing credentials array
- [x] Add CredentialSelectForm to the CompanyPage.js with is_owner authentication (non-owners will not see this content).
- [x] Add a variety of credentials from each group and check company data in api to see if assigned to that company.
