### ISSUE TITLE
USER STORY: Delete a Comment (CRUD)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#40]
As a user, I want to delete my own comments on a business’s profile so I can remove my comment if I change my mind.

**Acceptance Criteria:**

      1. When logged in, an authenticated user who is the comment 'owner' for a particular comment can click on a bin icon to delete the comment. 
      2. When deleted, the comment is removed from the Comments component of the company details page.
      3.

**Tasks:**

- [x] Create a handleDelete method in Comment component 
- [x] Add a test comment to a company and check that dots dropdown displays as the comment owner
- [x] Click on trash can to delete comment and check that comment removed from api
- [x] Check that comments_count reduces by 1 when a comment is deleted.
