### ISSUE TITLE
USER STORY: User Profile Page

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#45]
As a user, I want to add a profile avatar image to be displayed along with my name in the nav bar and next to my comments. 

**Acceptance Criteria:**

      1. When logged in, an authenticated user can click on a link to their own profile page and upload an image to be used alongside their username throughout the app.
      2. The user profile page header shows the number of companies that the user has endorsed and if the number of companies they own.
      3. The users own companies and their endorsed companies are displayed in the same way as the main company list.

**Tasks:**

- [x] Add profiles folder and ProfilePage file to pages directory
- [x] Add ProfilePage to routes and import to App.js  
- [x] Create layout Containers for Profile header (user's details), profileCompanies (owned by the user) and endorsedCompanies (endorsed by the user)
- [x] Create fetchData method to retrieve profile and companies data and setters to set the data for rendering.
- [x] Add profile data to the header including user name, image and counts of companies owned and endorsed.
- [x] Filter company data to create a profileCompanies list of companies where current user is also the company owner
- [x] Filter company data to create an endorsedCompanies list of companies where current user is also included in the endorsing_users array for that company instance.
- [x] Use mapping to display each list of companies in the relevant container using the CompanyList component.
- [x] Add styling to differentiate between the lists for the user to easily see which list is which.
