### ISSUE TITLE
USER STORY: Report a Comment

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#46]
As a user, I want to highlight a comment for review by an admin so that inappropriate content can be removed.

**Acceptance Criteria:**

      1. When logged in, an authenticated user can click on a flag next to each comment to display a button to 'report a comment'.
      2. Clicking on the flag displays a message asking if the user wishes to report this comment.
      3. By clicking on 'Yes' or 'No' buttons, the user can choose whether to report the comment for review by admin.
      4. When reported, the message flag is coloured orange with a note to confirm that this comment has been reported.

**Tasks:**

- [x] Add handleReport function to existing 'Comment' component so that when reported, the 'reported' field is set to true and the approved field is set to false.
- [x] Add flag icon with show / hide buttons const and conditional rendering to display buttons when showReportBtn = true 
- [x] Add conditional styling and rendering so that flag is coloured orange and reported text displays when comment reported
- [x] Add setComments function to re-render component and display comment with reported styling. 
- [x] Add message to confirm that comment has already been reported if both reported and showReportBtn are true
- [x] Check that the comment is added to AdminPage and listed under 'ReportedComments' when reported in CompanyPage.
- [x] Check that styling and messaging revert to normal (not reported) when comment approved by admin in AdminPage.
