### ISSUE TITLE
USER STORY: Consistent Styling and Responsiveness

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#48]
As a developer, I can set styling in module.css files relating to each component ensuring that the look and feel of the site is consistent across all pages, is fully responsive and is tailored to the needs of the user.

**Acceptance Criteria:**

     1. All pages and components of the site are consistent using react-bootstrap styles and are fully responsive on different devices.
      2. Instructions are clear, concise and easy to follow
      3. Visual cues, colour coding, and icons are used site-wide to enhance the UX
      4. Layouts are well spaced out with minimal distractions and unnecessary JavaScript code
      5. Font size is easily readable and passes all accessibility validation with excellent contrast

**Tasks:**

- [x] Review each page of the site and ensure that all components are displaying well in the REACT UI
- [x] Add icons and colour styling to buttons to ensure they stand out and have clear instruction
- [x] Review spacing on all page layouts and increase white space or reduce content where necessary to minimise distraction
- [x] Include clear instructions / call to action buttons so navigation is intuitive
