### ISSUE TITLE
USER STORY: WAVE and WCAG compatibility

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#49]
As a developer, I can ensure that all pages are configured correctly for page readers so that users of all abilities are able to navigate the site easily

**Acceptance Criteria:**

    1. All visual content has consistent and descriptive aria tags and alternative text wherever appropriate
    2. When passed through WAVE accessibility evaluation tool (https://wave.webaim.org/), all route paths pass with high ratings
    3. All WAVE accessibility evaluation results are included in project README.md file

**Tasks:**

- [x] Test the deployed site link through the wave website and check that there are no errors.
- [x] Resolve any errors that arise.
- [x] Screenshot the results to include in README
