### ISSUE TITLE
USER STORY: W3C validation (HTML)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#51]
As a developer, I can ensure that all HTML code is correct so that my site is accessible and performs well

**Acceptance Criteria:**

      1. All HTML pages pass through W3C validation with no major errors (https://validator.w3.org/)
      2.
      3.

**Tasks:**

- [x] Pass the deployed source code through the W3C html validation and check there are no errors.
- [x] Resolve any issues
- [x] Screenshot the results for inclusion in README.
