### ISSUE TITLE
USER STORY: W3C Jigsaw Validation (CSS)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#52]
As a developer, I can ensure that all CSS code is correct so that my site is accessible and performs well

**Acceptance Criteria:**

      1. All CSS code passes through W3C Jigsaw CSS validation with no major errors (https://jigsaw.w3.org/)
      2.
      3.

**Tasks:**

- [x] Pass each .css file in the react ui project through the validator
- [x] Address any issues and resolve them
- [x] Remove any commented out code
- [x] Screenshot the results to include in README
