### ISSUE TITLE
USER STORY: Python PEP8 Validation

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#53]
As a developer, I can ensure that all Python code is correct so that my site is accessible and performs well

**Acceptance Criteria:**

      1. All Python code passes through the CI Python Linter PEP8 validation with no major errors (https://pep8ci.herokuapp.com/)
      2. All code passes through flake8 checks within terminal.
      3.

**Tasks:**

- [x] Run python -m flake8 {name of resource} for each resource in the api and check that there are no errors (migration errors are n/a)
- [x] Paste each page of python code separately in the CI Python Linter to check that there are no errors.
- [x] Take screenshots of all results and add to the README
