### ISSUE TITLE
USER STORY: Delete My Business Listing (CRUD)

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#54]
As a business owner, I want to delete my listing so that customers are not viewing information for a business that no longer exists.

**Acceptance Criteria:**

     1. When logged in, an authenticated business owner can click a delete icon on a drop down menu in the company details page to request that the business listing be deleted.
     2. A security check to confirm that the owner wants the listing to be removed is shown
     3. Clicking on 'Cancel' takes the user back to the original business details page.

**Tasks:**

- [x] Add DotsDropdown component and module.css files
- [x] Create handleEdit and handleDelete methods and trigger using onClick listeners in associated menu item 
- [x] Import DotsDropdown in Company.js 
- [x] Add dropdown to render code to display in company detail page.
- [x] Click on three dots and select edit icon to check redirected to 'Page not found (not created editform yet).
- [x] Click on three dots and select delete icon to check if company deleted and removed from /companies in dev.
- [x] Check that the company details have also gone from the api and the relevant id is no longer listed.
