### ISSUE TITLE
USER STORY: View Endorsement and Comment Count

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#55]
As a user, I want to see how many endorsements and comments a company has so I can see if they are popular without having to view all of their details.

**Acceptance Criteria:**

      1. Users can view the number of endorsements that a company has next to an award icon
      2. Users can view the number of comments that a company listing has next to an icon of two speech bubbles
      3. The count increases and decreases as users add / remove endorsements and comments

**Tasks:**

- [x] Add jsx and Bootstrap styling to render appropriate award icon in Company and CompanyList components
- [x] Import endorsements_count and display next to the icon
- [x] Check that endorsements_count increases and decreases when an endorsement is added / removed
- [x] Add jsx and Bootstrap styling to render appropriate speech bubbles icon in Company and CompanyList components
- [x] Import comments_count and display next to the icon
- [x] Check that comments_count increases and decreases when an endorsement is added / removed
