### ISSUE TITLE
USER STORY: Set up REST App for each each data model

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#56]
As a developer I want to define and create an api for each of my models to create a framework for managing and storing all project data. 

**Acceptance Criteria:**

      1. An app exists for each model with the fields defined in a models.py file.
      2. Each model is associated with a serializers.py file to define model relationships and the data stored in the api.
      3. The urls and views for each model are defined within each resource app.

**Tasks:**

- [x] Add all required files to each resource app for Company, Comment, Endorsement, Profile, Credential models
- [x] Define the fields in the models.py file for each resource
- [x] Create serializers to manage the data and define relationships with other models 
- [x] Write views to process data into list and detail views where appropriate
