### ISSUE TITLE
USER STORY: Add a Logo and Website Link

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#6]
As a business owner, I want to upload a logo and link to my website so that potential customers can identify my brand and find out more about my business.

**Acceptance Criteria:**

      1. When completing the 'Add a Business' form the business owner can upload a logo image and add a link to their website
      2. The logo and website link are displayed along with an excerpt in the full directory listing
      3. Additional information such as the company's eco-credentials we also be displayed in the company detail listing

**Tasks:**

- [x] Include a 'logo' field in the Company model and in the CompanyCreateForm 
- [x] Set a default image and create a handleChangeImage method so that the user can alter their selection if they wish
- [x] Ensure that users can only upload an image by including accept="image/*" in the Form.File element
- [x] Add a test logo to the CompanyCreateForm to see if it shows in the preview, and click on Change the image to see if it allows you to select a different logo
- [x] Include a 'website' field in the Company model and in the CompanyCreateForm 
- [x] ensure that this field requires a url to be pasted into the field.
- [x] Enter data into the Company Website field that is not a url and check that an appropriate error is raised.
