### ISSUE TITLE
USER STORY: Set up Django Rest Framework GitHub Repository

### ISSUE THREAD

**Issue by sophie-thomson** [sophie-thomson/ecopositive-bristol-drf#9]
As a developer, I need to set up a separate repository to create the backend API using the Django Rest Framework which will manage and create json data to pass to the front end. 

**Acceptance Criteria:**

     1. New GitHub repository with appropriate name for PP5 DRF API Back End
     2. Able to use repository to create workspace in GitPod
     3. Working Add, Commit and Push functionality

**Tasks:**

- [x] Using CI Template, create new repository
- [x] Log into GitPod and create new Workspace for the new Repository
- [x] Use git add, commit and push for initial commit.
